package com.inteliger.portfel;

import java.awt.Choice;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Voltrix
 */
public class Paragon extends javax.swing.JFrame {
    
    /**
     * Creates new form Paragon
     */
    public Paragon() {
        initComponents();
    }

    GregorianCalendar kalendarz = new GregorianCalendar();
    ProgramContent content = new ProgramContent();
    Content_Menu menu = new Content_Menu();
    
    int monthNr;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        nrParagonu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sklepName = new javax.swing.JTextPane();
        NazwaSklepuLabel = new javax.swing.JLabel();
        DataLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        prodTable = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        anulujButton = new javax.swing.JButton();
        errorText = new javax.swing.JLabel();
        day = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(700, 250));
        setResizable(false);

        nrParagonu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nrParagonu.setText("Nowy Paragon");

        jScrollPane2.setViewportView(sklepName);

        NazwaSklepuLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NazwaSklepuLabel.setText("Nazwa Sklepu");

        DataLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DataLabel.setText("Data (d.m.r)");

        prodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nazwa Produktu", "Ilość", "Cena"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        prodTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(prodTable);

        saveButton.setText("Zapisz");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        anulujButton.setText("Anuluj");
        anulujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anulujButtonActionPerformed(evt);
            }
        });

        errorText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        errorText.setForeground(new java.awt.Color(255, 0, 0));

        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Styczeń", "Luty", "Marzec", "Kwiecień", "Maj", "Czerwiec", "Lipiec", "Sierpień", "Wrzesień", "Październik", "Listopad", "Grudzień" }));

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errorText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anulujButton))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DataLabel)
                            .addComponent(NazwaSklepuLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nrParagonu)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(month, 0, 84, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(nrParagonu)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DataLabel))
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(anulujButton)
                                .addComponent(saveButton))
                            .addComponent(errorText, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(NazwaSklepuLabel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anulujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anulujButtonActionPerformed
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_anulujButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        
        //WYWALANIE BŁĘDU
        
        if(sklepName.getText().isEmpty()){
            errorText.setText("Brak nazwy sklepu!");
        }
        else{
        
            //POBIERANIE NR PARAGONU I TWORZENIE NOWEGO PLIKU
            
            int nrParagonu;
            try {
                nrParagonu = content.getNrParagonu();
            } catch (FileNotFoundException ex) {
                System.out.println("NIE ZNALEZIONO PLIKU!");
                nrParagonu = 0;
            }
            int dzien = kalendarz.get(Calendar.DAY_OF_MONTH);
            int miesiac = kalendarz.get(Calendar.MONTH);
            miesiac += 1;
            int rok = kalendarz.get(Calendar.YEAR);

            String nazwa = nrParagonu+"_Paragon_"+dzien+"_"+miesiac+"_"+rok;

            File plik = new File("C:\\Users\\48602\\Desktop\\Paragony", nazwa);
            try {
                plik.createNewFile();
            } catch (IOException ex) {
                System.out.println("BŁĄD PRZY TWORZENIU PLIKU PARAGONU!");
            }
            
            try {
                FileWriter zapis = new FileWriter("C:\\Users\\48602\\Desktop\\Paragony"+nazwa);
                BufferedWriter w = new BufferedWriter(zapis);
                w.write("Paragon nr"+nrParagonu);
                w.newLine();
                w.write(sklepName.getText());
                w.newLine();
                w.write((String) day.getSelectedItem());
                w.write(".");
                if(month.getSelectedItem().equals("Styczeń")){
                    monthNr = 1;
                }
                else if(month.getSelectedItem().equals("Luty")){
                    monthNr = 2;
                }
                else if(month.getSelectedItem().equals("Marzec")){
                    monthNr = 3;
                }
                else if(month.getSelectedItem().equals("Kwiecień")){
                    monthNr = 4;
                }
                else if(month.getSelectedItem().equals("Maj")){
                    monthNr = 5;
                }
                else if(month.getSelectedItem().equals("Czerwiec")){
                    monthNr = 6;
                }
                else if(month.getSelectedItem().equals("Lipiec")){
                    monthNr = 7;
                }
                else if(month.getSelectedItem().equals("Sierpień")){
                    monthNr = 8;
                }
                else if(month.getSelectedItem().equals("Wrzesień")){
                    monthNr = 9;
                }
                else if(month.getSelectedItem().equals("Październik")){
                    monthNr = 10;
                }
                else if(month.getSelectedItem().equals("Listopad")){
                    monthNr = 11;
                }
                else if(month.getSelectedItem().equals("Grudzień")){
                    monthNr = 12;
                }
                w.write(monthNr);
                w.write(".");
                w.write((String) year.getSelectedItem());
                w.newLine();
                boolean stop = false;
                int rowCount = 1;
                int columnCount = 1;
                String produkt;
                int ilosc;
                int cena;
                /*while(stop){
                    int countTable = prodTable.getColumnCount();
                    boolean isBlank = false;
                    while(isBlank){
                        while(columnCount<=prodTable.getColumnCount()){
                            if(prodTable.getValueAt(rowCount, columnCount).equals(null)){
                                isBlank = true;
                                break;
                            }
                            else{
                                
                            }
                        }
                    }
                }*/
                for (int i = 0; i<=prodTable.getColumnCount();i++){
                    for(int j = 0;j<=prodTable.getRowCount();j++){
                        if(j==0){
                            produkt = (String) prodTable.getValueAt(j, i);
                            w.write(produkt);
                        }
                        else if(j==1){
                            ilosc = (int) prodTable.getValueAt(j, i);
                            w.write(" Ilość: "+ilosc);
                        }
                        else if(j==2){
                            cena = (int) prodTable.getValueAt(j, i);
                            w.write(" Cena: "+cena+" zł");
                        }
                    }
                }
                w.close();
            } catch (IOException ex) {
                System.out.println("BŁĄD");
            }
            

            //USTAWIANIE NOWEGO NUMERU PARAGONU
            
            try {
                content.setShopNumber();
            } catch (IOException ex) {
                System.out.println("NIE ZNALEZIONO PLIKU!");
            }

            this.setVisible(false);
            menu.setVisible(true);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paragon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paragon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paragon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paragon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paragon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DataLabel;
    private javax.swing.JLabel NazwaSklepuLabel;
    private javax.swing.JButton anulujButton;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JLabel errorText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JLabel nrParagonu;
    private javax.swing.JTable prodTable;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextPane sklepName;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
