/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.inteliger.portfel;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author 48602
 */
public class Pensja extends javax.swing.JFrame {

    GregorianCalendar kalendarz = new GregorianCalendar();
    Content_Menu menu = new Content_Menu();
    
    public Pensja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NazwaFrame = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nazwaFirmyPane = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        kwotaPane = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        ilGodzinPane = new javax.swing.JTextPane();
        NazwaFirmy = new javax.swing.JLabel();
        Kwota = new javax.swing.JLabel();
        IloscGodzin = new javax.swing.JLabel();
        anulujB = new javax.swing.JButton();
        zapiszB = new javax.swing.JButton();
        errorText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(700, 400));

        NazwaFrame.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        NazwaFrame.setText("Pensja");

        jScrollPane1.setViewportView(nazwaFirmyPane);

        jScrollPane2.setViewportView(kwotaPane);

        jScrollPane3.setViewportView(ilGodzinPane);

        NazwaFirmy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NazwaFirmy.setText("Nazwa Firmy");

        Kwota.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Kwota.setText("Kwota");

        IloscGodzin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IloscGodzin.setText("Ilość godzin");

        anulujB.setText("Anuluj");
        anulujB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anulujBActionPerformed(evt);
            }
        });

        zapiszB.setText("Zapisz");
        zapiszB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapiszBActionPerformed(evt);
            }
        });

        errorText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        errorText.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NazwaFirmy)
                    .addComponent(Kwota)
                    .addComponent(IloscGodzin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errorText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(zapiszB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anulujB)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(NazwaFrame)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NazwaFrame)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NazwaFirmy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Kwota)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IloscGodzin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(anulujB)
                        .addComponent(zapiszB)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anulujBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anulujBActionPerformed
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_anulujBActionPerformed

    private void zapiszBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapiszBActionPerformed
        
        //BŁĄD TEKSTOWY PRZY PUSTYCH POLACH
        
        if(nazwaFirmyPane.getText().isEmpty()){
            errorText.setText("Brak podanej nazwy firmy!");
        }
        else if(kwotaPane.getText().isEmpty()){
            errorText.setText("Brak podanej kwoty!");
        }
        else if(ilGodzinPane.getText().isEmpty()){
            errorText.setText("Brak podanej ilości godzin!");
        }
        else{
            
            //POBIERANIE NUMERU PLIKU PENSJI
            
            ProgramContent kontent = new ProgramContent();

            int nrPensji;
            try {
                nrPensji = kontent.getNrPensji();
            } catch (FileNotFoundException ex) {
                System.out.println("BŁĄD");
                nrPensji = 0;
            }
            
            //TWORZENIE NOWEGO PLIKU TEKSTOWEGO I POBIERANIE AKTUALNEJ DATY
            
            int dzien = kalendarz.get(Calendar.DAY_OF_MONTH);
            int miesiac = kalendarz.get(Calendar.MONTH+2);
            miesiac += 1;
            int rok = kalendarz.get(Calendar.YEAR);

            String nazwa = nrPensji+"_Pensja_"+dzien+"."+miesiac+"."+rok+".txt";

            File plik = new File("C:\\Users\\48602\\Desktop\\Pensje", nazwa);
            try {
                plik.createNewFile();
            } catch (IOException ex) {
                System.out.println("BŁĄD");
            }

            
            //ZAPISYWANIE DANYCH DO PLIKU TEKSTOWEGO
            
            String nazwaFirmy = nazwaFirmyPane.getText();
            String kwota = kwotaPane.getText();
            String ilGodzin = ilGodzinPane.getText();
            
            try {
                FileWriter pensjaText = new FileWriter("C:\\Users\\48602\\Desktop\\Pensje\\"+nazwa);
                BufferedWriter w = new BufferedWriter(pensjaText);
                w.write("Pensja nr: "+nrPensji);
                w.newLine();
                w.write(nazwaFirmy);
                w.newLine();
                w.write(kwota);
                w.newLine();
                w.write(ilGodzin);
                w.close();
            } catch (IOException ex) {
                System.out.println("BŁĄD");
            }
            
            
            //DODAWANIE KOLEJNEJ LICZBY DO SCHOWKA moduleWallet.txt
            
            try {
                kontent.setModuleNumber();
            } catch (FileNotFoundException ex) {
                System.out.println("BŁĄD przy znalezieniu pliku");
            } catch (UnsupportedEncodingException ex) {
                System.out.println("BŁĄD problem z zapisem");
            } catch (IOException ex) {
                System.out.println("BŁĄD");
            }
            this.setVisible(false);
            menu.setVisible(true);
        }
    }//GEN-LAST:event_zapiszBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pensja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pensja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pensja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pensja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pensja().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IloscGodzin;
    private javax.swing.JLabel Kwota;
    private javax.swing.JLabel NazwaFirmy;
    private javax.swing.JLabel NazwaFrame;
    private javax.swing.JButton anulujB;
    private javax.swing.JLabel errorText;
    private javax.swing.JTextPane ilGodzinPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane kwotaPane;
    private javax.swing.JTextPane nazwaFirmyPane;
    private javax.swing.JButton zapiszB;
    // End of variables declaration//GEN-END:variables
}